apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  creationTimestamp: "2023-01-24T00:41:56Z"
  generation: 1
  name: test-operatorhubio-catalog
  namespace: olm
spec:
  displayName: Community Operators
  image: quay.io/operatorhubio/catalog:latest
  publisher: OperatorHub.io
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 60m
